apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vn8ayhttl-nodejs 
  janus-idp.io/tekton: vn8ayhttl-nodejs
  backstage.io/kubernetes-id: vn8ayhttl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vn8ayhttl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  